### ISSUE TITLE
Using a vsphere `folder` seems to be mandatory for the use of vsphere.

### ISSUE THREAD

**Issue by mooperd** [kubermatic/kubeone#740]
Hi, 

I'm trying to deploy kubeone on vsphere but I am getting errors - Not sure where to go from here.

Cheers,

Andrew

Command
`kubeone install config.yaml -t examples/terraform/vsphere/``

config.yaml
```
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
versions:
  kubernetes: '1.16.2'
cloudProvider:
  name: 'vsphere'
  cloudConfig: |
    [Global]
    secret-name = "cloud-provider-credentials"
    secret-namespace = "kube-system"
    port = "443"
    insecure-flag = "1"

    [VirtualCenter "lab-vcsa.lab.local"]

    [Workspace]
    server = "lab-vcsa.lab.local"
    datacenter = "Datacenter"
    default-datastore="vsanDatastore"
    resourcepool-path="kubeone"

    [Disk]
    scsicontrollertype = pvscsi

    [Network]
    public-network = "DPortgroup-192.168.10.X" 
```

Error
```
WARN[20:05:38 UTC] Task failed…                                 
Error: failed to init kubernetes on leader: + [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm token create 8zj19f.cnz9nnvl50yuyixt --ttl 1h
timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm  token create 8zj19f.cnz9nnvl50yuyixt --ttl 1h
	exit 0;
fi
sudo kubeadm  init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1
failed to init kubernetes on leader: + [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm token create 8zj19f.cnz9nnvl50yuyixt --ttl 1h
timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm  token create 8zj19f.cnz9nnvl50yuyixt --ttl 1h
	exit 0;
fi
sudo kubeadm  init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1
```

terraform output
```
kubeone_api = {
  "endpoint" = "192.168.10.167"
}
kubeone_hosts = {
  "control_plane" = {
    "cloud_provider" = "vsphere"
    "cluster_name" = "andrew"
    "private_address" = []
    "public_address" = [
      "192.168.10.169",
      "192.168.10.168",
      "192.168.10.166",
    ]
    "ssh_agent_socket" = "env:SSH_AUTH_SOCK"
    "ssh_port" = 22
    "ssh_private_key_file" = ""
    "ssh_user" = "ubuntu"
  }
}
kubeone_workers = {
  "andrew-pool1" = {
    "providerSpec" = {
      "cloudProviderSpec" = {
        "allowInsecure" = false
        "cluster" = "cluster1"
        "cpus" = 2
        "datacenter" = "Datacenter"
        "datastore" = "vsanDatastore"
        "diskSizeGB" = 10
        "memoryMB" = 2048
        "templateVMName" = "ubuntu-bionic-18.04-cloudimg-20191125"
        "vmNetName" = "DPortgroup-192.168.10.X"
      }
      "operatingSystem" = "ubuntu"
      "operatingSystemSpec" = {
        "distUpgradeOnBoot" = false
      }
      "sshPublicKeys" = [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/F1uFMNLYkbIxHckClpedBp2VriufM57F4l6nwIKxziDIP54Ql1kMt4m51XFRBv07ZqLX4p5IgdHp/qwB5/FYy5bRuYEWixtgLwLixvYILJzmzfeH8MMGIYsTXluY6YVVtBlsxr3fF5t7HNXN9e1eeogHxaOZzy1iTa08rJjUH3Sawo+Z5k8DOIJjcvMNBwjtsiWvhOdyz/P8N2XT8t0qSweTpFrkxKsC21HQEbfkkcMOaDYzYyURuHu6B1y75rJGFyPFBTkBc23nchyZc+Y8vq5GPN8dh6WGQj6zMJHtbDs4Pwk0GCgYr3M7QVzMZk1eoDdt5/Hjb6ztiJnyREy5 ubuntu@admin-workstation\n",
      ]
    }
    "replicas" = 1
  }
}
```

**Comment by xmudrii** [comment]
The `kubeadm token create` command is supposed to be executed only if a cluster already exists on the given infrastructure. If you have never provisioned a cluster, that step should be skipped.

In such cases, if you are sure that there is no cluster or that it's safe to unprovision it, you can run `kubeone reset config.yaml -t examples/terraform/vsphere/` and it will unprovision Kubernetes and revert the most of tasks done by KubeOne so far.

**Comment by mooperd** [comment]
Hi, Is there any workaround? I am getting this error consistently when trying to deploy fresh clusters on vsphere.

**Comment by xmudrii** [comment]
Have you tried running `kubeone reset`? If yes, are you getting the same error when running `kubeone install` the next time?

After running `kubeone reset`, you can also SSH into nodes and verify that there is no `/etc/kubernetes` directory. If it is there, delete it. The next time you run `kubeone install` it should either work or return a different error.

**Comment by xmudrii** [comment]
@mooperd We have merged a fix that is supposed to improve the handling of the vSphere credentials secret (#737). Maybe that was the root of the problem. You can grab KubeOne from master and try again. Just make sure to run `kubeone reset` to revert what has been done by `kubeone install`.

**Comment by mooperd** [comment]
I am still getting the same error using master. I have created a script to make everything consistent.

I have a feeling that I am misunderstanding the difference between "VirtualCenter" and "Workspace.server" in the config. I couldn't find any clarification in the docs. I'm also not able to parse the output of the error - it's somewhat mangled verbose bash output.

In the tf I have removed all the load balancer stuff and set the number of masters to 1.

I am using this script to do everything - I am tearing down everything and redoing from scratch with each attempt. 

```bash
export VSPHERE_ALLOW_UNVERIFIED_SSL=true
export VSPHERE_SERVER=192.168.10.10
export VSPHERE_USER=Administrator@vsphere.local
export VSPHERE_PASSWORD=ChangeMe1337!
export VSPHERE_DATACENTER=Datacenter
export VSPHERE_DATASTORE=vsanDatastore
export VSPHERE_CLUSTER=cluster1
export VSPHERE_NETWORK=DPortgroup-192.168.10.X
export VSPHERE_POOL=andrew-kubeone
export TEMPLATE_IMAGE=ubuntu-bionic-18.04-cloudimg-20191125

terraform apply -var="cluster_name=andrew"\
	       -var="dc_name=$VSPHERE_DATACENTER"\
               -var="datastore_name=$VSPHERE_DATASTORE"\
	       -var="compute_cluster_name=$VSPHERE_CLUSTER"\
	       -var="network_name=$VSPHERE_NETWORK"\
	       -var="template_name=$TEMPLATE_IMAGE"\
	examples/terraform/vsphere/

cat << EOF > KubeOneCluster.yaml
apiVersion: kubeone.io/v1alpha1
kind: KubeOneCluster
versions:
  kubernetes: '1.16.2'
cloudProvider:
  name: 'vsphere'
  cloudConfig: |
    [Global]
    secret-name = "cloud-provider-credentials"
    secret-namespace = "kube-system"
    port = "443"
    insecure-flag = "0"

    [VirtualCenter "$VSPHERE_SERVER"]

    [Workspace]
    server = "$VSPHERE_SERVER"
    datacenter = "$VSPHERE_DATACENTER"
    default-datastore="$VSPHERE_DATASTORE"
    resourcepool-path="$VSPHERE_POOL"

    [Disk]
    scsicontrollertype = pvscsi

    [Network]
    public-network = "$VSPHERE_NETWORK"
EOF

kubeone install KubeOneCluster.yaml --tfjson .
```

output
```
$ bash hit-it.sh 
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_compute_cluster.cluster: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
vsphere_virtual_machine.control_plane[0]: Refreshing state... [id=4233e9c7-529c-251b-f7d6-4e60c5cfe320]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

kubeone_hosts = {
  "control_plane" = {
    "cloud_provider" = "vsphere"
    "cluster_name" = "andrew"
    "private_address" = []
    "public_address" = [
      "192.168.10.181",
    ]
    "ssh_agent_socket" = "env:SSH_AUTH_SOCK"
    "ssh_port" = 22
    "ssh_private_key_file" = ""
    "ssh_user" = "ubuntu"
  }
}
kubeone_workers = {
  "andrew-pool1" = {
    "providerSpec" = {
      "cloudProviderSpec" = {
        "allowInsecure" = false
        "cluster" = "cluster1"
        "cpus" = 2
        "datacenter" = "Datacenter"
        "datastore" = "vsanDatastore"
        "diskSizeGB" = 10
        "memoryMB" = 2048
        "templateVMName" = "ubuntu-bionic-18.04-cloudimg-20191125"
        "vmNetName" = "DPortgroup-192.168.10.X"
      }
      "operatingSystem" = "ubuntu"
      "operatingSystemSpec" = {
        "distUpgradeOnBoot" = false
      }
      "sshPublicKeys" = [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW9fPeuDT4mOj55tacQ0bylB2yMJ3fwb4iMkU1k4Wc2ecv8MLAPHY1fyohpjA/fQJlRUvB/TrmFS4QDF0JVc3b4AIzLiOjjpJ8AQQhkDYJDwbIF8Z26Gm3QbTo99Qm4irmGMipDM2AHI/l19qWfhpnvMt/W3cHl/mCd9+XEsNmqI/mPTs5x6TWi2FHEEx5jLU0sCteR2DlPlICuqfC2A6eISDepXepMR+TdeaZ5EO78Fzaqrlrs3Msegxih31aAeaCbAbG15MXVAN3CZesRuZs1A8Sm6nsEsfFsgqtqAtVDHTiIEX6WjYfzOdR/lyDKgtJHdhoGuFtEAmGofJgSWWp ubuntu@admin-workstation\n",
      ]
    }
    "replicas" = 1
  }
}
INFO[13:42:00 UTC] Installing prerequisites…                    
INFO[13:42:00 UTC] Determine operating system…                   node=192.168.10.181
INFO[13:42:02 UTC] Determine hostname…                           node=192.168.10.181
INFO[13:42:02 UTC] Creating environment file…                    node=192.168.10.181
INFO[13:42:02 UTC] Installing kubeadm…                           node=192.168.10.181 os=ubuntu
INFO[13:42:46 UTC] Deploying configuration files…                node=192.168.10.181 os=ubuntu
INFO[13:42:46 UTC] Generating kubeadm config file…              
INFO[13:42:46 UTC] Configuring certs and etcd on first controller… 
INFO[13:42:46 UTC] Ensuring Certificates…                        node=192.168.10.181
INFO[13:42:48 UTC] Downloading PKI…                             
INFO[13:42:48 UTC] Downloading PKI files…                        node=192.168.10.181
INFO[13:42:48 UTC] Creating local backup…                        node=192.168.10.181
INFO[13:42:48 UTC] Deploying PKI…                               
INFO[13:42:48 UTC] Configuring certs and etcd on consecutive controller… 
INFO[13:42:48 UTC] Initializing Kubernetes on leader…           
INFO[13:42:48 UTC] Running kubeadm…                              node=192.168.10.181
WARN[13:45:05 UTC] Task failed…                                 
WARN[13:45:10 UTC] Retrying task…                               
INFO[13:45:10 UTC] Initializing Kubernetes on leader…           
INFO[13:45:10 UTC] Running kubeadm…                              node=192.168.10.181
WARN[13:46:25 UTC] Task failed…                                 
WARN[13:46:35 UTC] Retrying task…                               
INFO[13:46:35 UTC] Initializing Kubernetes on leader…           
INFO[13:46:35 UTC] Running kubeadm…                              node=192.168.10.181
WARN[13:47:50 UTC] Task failed…                                 
Error: failed to init kubernetes on leader: + [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm token create bp8o0u.6ekrntjevkbewbcw --ttl 1h
timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm  token create bp8o0u.6ekrntjevkbewbcw --ttl 1h
	exit 0;
fi
sudo kubeadm  init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1
failed to init kubernetes on leader: + [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm token create bp8o0u.6ekrntjevkbewbcw --ttl 1h
timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm  token create bp8o0u.6ekrntjevkbewbcw --ttl 1h
	exit 0;
fi
sudo kubeadm  init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1
```

**Comment by kron4eg** [comment]
You could try `kubeone install -v`, this will also increase verbosity on kubeadm.

**Comment by mooperd** [comment]
This is the output with -v

```
DEBU[14:20:20 UTC] Executing `terraform output -json` to query terraform state 
INFO[14:20:20 UTC] Installing prerequisites…                    
INFO[14:20:20 UTC] Determine operating system…                   node=192.168.10.181
[192.168.10.181] + . /etc/os-release
[192.168.10.181] ++ NAME=Ubuntu
[192.168.10.181] ++ VERSION='18.04.3 LTS (Bionic Beaver)'
[192.168.10.181] ++ ID=ubuntu
[192.168.10.181] ++ ID_LIKE=debian
[192.168.10.181] ++ PRETTY_NAME='Ubuntu 18.04.3 LTS'
[192.168.10.181] ++ VERSION_ID=18.04
[192.168.10.181] ++ HOME_URL=https://www.ubuntu.com/
[192.168.10.181] ++ SUPPORT_URL=https://help.ubuntu.com/
[192.168.10.181] ++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
[192.168.10.181] ++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
[192.168.10.181] ++ VERSION_CODENAME=bionic
[192.168.10.181] ++ UBUNTU_CODENAME=bionic
[192.168.10.181] + echo -n ubuntu
[192.168.10.181] ubuntu
INFO[14:20:21 UTC] Determine hostname…                           node=192.168.10.181
[192.168.10.181] ++ hostname -f
[192.168.10.181] andrew-cp-1
[192.168.10.181] + fqdn=andrew-cp-1
[192.168.10.181] + '[' andrew-cp-1 = localhost ']'
[192.168.10.181] + echo andrew-cp-1
INFO[14:20:21 UTC] Creating environment file…                    node=192.168.10.181
[192.168.10.181] + sudo mkdir -p /etc/kubeone
[192.168.10.181] + sudo tee /etc/kubeone/proxy-env
[192.168.10.181] + cat
[192.168.10.181] 
[192.168.10.181] + envtmp=/tmp/k1-etc-environment
[192.168.10.181] + grep -v '#kubeone$' /etc/environment
[192.168.10.181] + set +o pipefail
[192.168.10.181] + grep = /etc/kubeone/proxy-env
[192.168.10.181] + sed 's/$/#kubeone/'
[192.168.10.181] + sudo tee /etc/environment
[192.168.10.181] PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
INFO[14:20:21 UTC] Installing kubeadm…                           node=192.168.10.181 os=ubuntu
[192.168.10.181] + sudo swapoff -a
[192.168.10.181] + sudo sed -i '/.*swap.*/d' /etc/fstab
[192.168.10.181] + . /etc/os-release
[192.168.10.181] ++ NAME=Ubuntu
[192.168.10.181] ++ VERSION='18.04.3 LTS (Bionic Beaver)'
[192.168.10.181] ++ ID=ubuntu
[192.168.10.181] ++ ID_LIKE=debian
[192.168.10.181] ++ PRETTY_NAME='Ubuntu 18.04.3 LTS'
[192.168.10.181] ++ VERSION_ID=18.04
[192.168.10.181] ++ HOME_URL=https://www.ubuntu.com/
[192.168.10.181] ++ SUPPORT_URL=https://help.ubuntu.com/
[192.168.10.181] ++ BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu/
[192.168.10.181] ++ PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
[192.168.10.181] ++ VERSION_CODENAME=bionic
[192.168.10.181] ++ UBUNTU_CODENAME=bionic
[192.168.10.181] + . /etc/kubeone/proxy-env
[192.168.10.181] + type docker
[192.168.10.181] + type kubelet
[192.168.10.181] + exit 0
INFO[14:20:21 UTC] Deploying configuration files…                node=192.168.10.181 os=ubuntu
[192.168.10.181] + sudo mkdir -p /etc/systemd/system/kubelet.service.d/ /etc/kubernetes
[192.168.10.181] + sudo mv ./kubeone/cfg/cloud-config /etc/kubernetes/cloud-config
[192.168.10.181] + sudo chown root:root /etc/kubernetes/cloud-config
[192.168.10.181] + sudo chmod 600 /etc/kubernetes/cloud-config
[192.168.10.181] + [[ -f ./kubeone/cfg/audit-policy.yaml ]]
INFO[14:20:21 UTC] Generating kubeadm config file…              
INFO[14:20:21 UTC] Configuring certs and etcd on first controller… 
INFO[14:20:21 UTC] Ensuring Certificates…                        node=192.168.10.181
+ [[ -d ./kubeone/pki ]]
+ sudo rsync -av ./kubeone/pki/ /etc/kubernetes/pki/
sending incremental file list
./
ca.crt
ca.key
front-proxy-ca.crt
front-proxy-ca.key
etcd/
etcd/ca.crt
etcd/ca.key

sent 8,645 bytes  received 147 bytes  17,584.00 bytes/sec
total size is 10,239  speedup is 1.16
+ sudo chown -R root:root /etc/kubernetes
+ rm -rf ./kubeone/pki
+ sudo kubeadm --v=6 init phase certs all --config=./kubeone/cfg/master_0.yaml
I1129 14:20:21.783321   15077 initconfiguration.go:190] loading configuration from "./kubeone/cfg/master_0.yaml"
[config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta2, Kind=JoinConfiguration
I1129 14:20:21.787163   15077 initconfiguration.go:102] detected and using CRI socket: /var/run/dockershim.sock
I1129 14:20:21.787645   15077 feature_gate.go:216] feature gates: &{map[]}
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
I1129 14:20:21.792098   15077 certs.go:70] creating a new public/private key files for signing service account users
[certs] Using the existing "sa" key
INFO[14:20:21 UTC] Downloading PKI…                             
+ mkdir -p ./kubeone/pki/etcd
+ sudo cp /etc/kubernetes/pki/ca.crt ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/ca.key ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/sa.key ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/sa.pub ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/front-proxy-ca.crt ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/front-proxy-ca.key ./kubeone/pki/
+ sudo cp /etc/kubernetes/pki/etcd/ca.crt /etc/kubernetes/pki/etcd/ca.key ./kubeone/pki/etcd/
++ id -u
++ id -g
+ sudo chown -R 1000:1000 ./kubeone
INFO[14:20:21 UTC] Downloading PKI files…                        node=192.168.10.181
INFO[14:20:21 UTC] Creating local backup…                        node=192.168.10.181
INFO[14:20:21 UTC] Deploying PKI…                               
INFO[14:20:21 UTC] Configuring certs and etcd on consecutive controller… 
INFO[14:20:21 UTC] Initializing Kubernetes on leader…           
INFO[14:20:21 UTC] Running kubeadm…                              node=192.168.10.181
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm --v=6 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h
I1129 14:20:21.922668   15107 token.go:115] [token] validating mixed arguments
I1129 14:20:21.922849   15107 token.go:122] [token] getting Clientsets from kubeconfig file
I1129 14:20:21.922913   15107 cmdutil.go:79] Using kubeconfig file: /etc/kubernetes/admin.conf
I1129 14:20:21.924640   15107 loader.go:375] Config loaded from file:  /etc/kubernetes/admin.conf
I1129 14:20:21.926032   15107 token.go:221] [token] loading configurations
I1129 14:20:21.926434   15107 interface.go:384] Looking for default routes with IPv4 addresses
I1129 14:20:21.926486   15107 interface.go:389] Default route transits interface "ens192"
I1129 14:20:21.926730   15107 interface.go:196] Interface ens192 is up
I1129 14:20:21.926930   15107 interface.go:244] Interface "ens192" has 2 addresses :[192.168.10.181/24 fe80::250:56ff:feb3:65ae/64].
I1129 14:20:21.927000   15107 interface.go:211] Checking addr  192.168.10.181/24.
I1129 14:20:21.927045   15107 interface.go:218] IP found 192.168.10.181
I1129 14:20:21.927128   15107 interface.go:250] Found valid IPv4 address 192.168.10.181 for interface "ens192".
I1129 14:20:21.927166   15107 interface.go:395] Found active IP 192.168.10.181 
I1129 14:20:21.927478   15107 feature_gate.go:216] feature gates: &{map[]}
I1129 14:20:21.927539   15107 token.go:233] [token] creating token
I1129 14:20:21.928914   15107 round_trippers.go:443] GET https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets/bootstrap-token-swa4aj  in 0 milliseconds
I1129 14:20:21.929629   15107 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:20:26.930826   15107 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:20:36.931850   15107 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:20:56.932849   15107 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:21:36.933823   15107 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
timed out waiting for the condition
WARN[14:21:36 UTC] Task failed…                                 
WARN[14:21:36 UTC] error was: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm --v=6 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h
	exit 0;
fi
sudo kubeadm --v=6 init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1 
WARN[14:21:41 UTC] Retrying task…                               
INFO[14:21:41 UTC] Initializing Kubernetes on leader…           
INFO[14:21:41 UTC] Running kubeadm…                              node=192.168.10.181
+ [[ -f /etc/kubernetes/admin.conf ]]
+ sudo kubeadm --v=6 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h
I1129 14:21:41.993001   15486 token.go:115] [token] validating mixed arguments
I1129 14:21:41.993060   15486 token.go:122] [token] getting Clientsets from kubeconfig file
I1129 14:21:41.993082   15486 cmdutil.go:79] Using kubeconfig file: /etc/kubernetes/admin.conf
I1129 14:21:41.994617   15486 loader.go:375] Config loaded from file:  /etc/kubernetes/admin.conf
I1129 14:21:41.995990   15486 token.go:221] [token] loading configurations
I1129 14:21:41.996146   15486 interface.go:384] Looking for default routes with IPv4 addresses
I1129 14:21:41.996150   15486 interface.go:389] Default route transits interface "ens192"
I1129 14:21:41.996316   15486 interface.go:196] Interface ens192 is up
I1129 14:21:41.996356   15486 interface.go:244] Interface "ens192" has 2 addresses :[192.168.10.181/24 fe80::250:56ff:feb3:65ae/64].
I1129 14:21:41.996369   15486 interface.go:211] Checking addr  192.168.10.181/24.
I1129 14:21:41.996375   15486 interface.go:218] IP found 192.168.10.181
I1129 14:21:41.996381   15486 interface.go:250] Found valid IPv4 address 192.168.10.181 for interface "ens192".
I1129 14:21:41.996385   15486 interface.go:395] Found active IP 192.168.10.181 
I1129 14:21:41.996626   15486 feature_gate.go:216] feature gates: &{map[]}
I1129 14:21:41.996651   15486 token.go:233] [token] creating token
I1129 14:21:41.997413   15486 round_trippers.go:443] GET https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets/bootstrap-token-swa4aj  in 0 milliseconds
I1129 14:21:41.998005   15486 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:21:46.998840   15486 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:21:56.999566   15486 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:22:17.000206   15486 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 14:22:57.001204   15486 round_trippers.go:443] POST https://192.168.10.181:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
timed out waiting for the condition
WARN[14:22:57 UTC] Task failed…                                 
WARN[14:22:57 UTC] error was: failed to exec command: export "PATH=$PATH:/sbin:/usr/local/bin:/opt/bin"

set -xeu pipefail


if [[ -f /etc/kubernetes/admin.conf ]]; then
	sudo kubeadm --v=6 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h
	exit 0;
fi
sudo kubeadm --v=6 init --config=./kubeone/cfg/master_0.yaml
: Process exited with status 1 
WARN[14:23:07 UTC] Retrying task…   
```

**Comment by kron4eg** [comment]
Are you sure you did `kubeone reset` before running `kubeone install`?

**Comment by mooperd** [comment]
In my script I have terraform destroy; terraform apply. I am starting with fresh infrastructure each time. Is there some state somewhere else I should be careful of?

**Comment by kron4eg** [comment]
OK, sounds good. So after it fails next time, can you please ssh to your `192.168.10.181`
and run manually `sudo kubeadm --v=10 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h`.

**Comment by mooperd** [comment]
```
ubuntu@andrew-cp-1:~$ sudo kubeadm --v=10 token create swa4aj.jjz70dv29lkfg2g2 --ttl 1h
I1129 15:31:37.962429    8460 token.go:115] [token] validating mixed arguments
I1129 15:31:37.962536    8460 token.go:122] [token] getting Clientsets from kubeconfig file
I1129 15:31:37.962556    8460 cmdutil.go:79] Using kubeconfig file: /etc/kubernetes/admin.conf
I1129 15:31:37.964336    8460 loader.go:375] Config loaded from file:  /etc/kubernetes/admin.conf
I1129 15:31:37.965205    8460 token.go:221] [token] loading configurations
I1129 15:31:37.965405    8460 interface.go:384] Looking for default routes with IPv4 addresses
I1129 15:31:37.965435    8460 interface.go:389] Default route transits interface "ens192"
I1129 15:31:37.965597    8460 interface.go:196] Interface ens192 is up
I1129 15:31:37.965680    8460 interface.go:244] Interface "ens192" has 2 addresses :[192.168.10.184/24 fe80::250:56ff:feb3:9b6a/64].
I1129 15:31:37.965699    8460 interface.go:211] Checking addr  192.168.10.184/24.
I1129 15:31:37.965709    8460 interface.go:218] IP found 192.168.10.184
I1129 15:31:37.965718    8460 interface.go:250] Found valid IPv4 address 192.168.10.184 for interface "ens192".
I1129 15:31:37.965726    8460 interface.go:395] Found active IP 192.168.10.184 
I1129 15:31:37.966086    8460 feature_gate.go:216] feature gates: &{map[]}
I1129 15:31:37.966142    8460 token.go:233] [token] creating token
I1129 15:31:37.966232    8460 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets/bootstrap-token-swa4aj'
I1129 15:31:37.966666    8460 round_trippers.go:443] GET https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets/bootstrap-token-swa4aj  in 0 milliseconds
I1129 15:31:37.966737    8460 round_trippers.go:449] Response Headers:
I1129 15:31:37.967192    8460 request.go:968] Request Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"bootstrap-token-swa4aj","namespace":"kube-system","creationTimestamp":null},"data":{"auth-extra-groups":"c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=","expiration":"MjAxOS0xMS0yOVQxNjozMTozN1o=","token-id":"c3dhNGFq","token-secret":"amp6NzBkdjI5bGtmZzJnMg==","usage-bootstrap-authentication":"dHJ1ZQ==","usage-bootstrap-signing":"dHJ1ZQ=="},"type":"bootstrap.kubernetes.io/token"}
I1129 15:31:37.967429    8460 round_trippers.go:423] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets'
I1129 15:31:37.967800    8460 round_trippers.go:443] POST https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 15:31:37.967831    8460 round_trippers.go:449] Response Headers:
I1129 15:31:42.968269    8460 request.go:968] Request Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"bootstrap-token-swa4aj","namespace":"kube-system","creationTimestamp":null},"data":{"auth-extra-groups":"c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=","expiration":"MjAxOS0xMS0yOVQxNjozMTozN1o=","token-id":"c3dhNGFq","token-secret":"amp6NzBkdjI5bGtmZzJnMg==","usage-bootstrap-authentication":"dHJ1ZQ==","usage-bootstrap-signing":"dHJ1ZQ=="},"type":"bootstrap.kubernetes.io/token"}
I1129 15:31:42.968361    8460 round_trippers.go:423] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets'
I1129 15:31:42.968651    8460 round_trippers.go:443] POST https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 15:31:42.968716    8460 round_trippers.go:449] Response Headers:
I1129 15:31:52.969743    8460 request.go:968] Request Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"bootstrap-token-swa4aj","namespace":"kube-system","creationTimestamp":null},"data":{"auth-extra-groups":"c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=","expiration":"MjAxOS0xMS0yOVQxNjozMTozN1o=","token-id":"c3dhNGFq","token-secret":"amp6NzBkdjI5bGtmZzJnMg==","usage-bootstrap-authentication":"dHJ1ZQ==","usage-bootstrap-signing":"dHJ1ZQ=="},"type":"bootstrap.kubernetes.io/token"}
I1129 15:31:52.970106    8460 round_trippers.go:423] curl -k -v -XPOST  -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" -H "Accept: application/json, */*" -H "Content-Type: application/json" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets'
I1129 15:31:52.970749    8460 round_trippers.go:443] POST https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 15:31:52.970791    8460 round_trippers.go:449] Response Headers:
I1129 15:32:12.971440    8460 request.go:968] Request Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"bootstrap-token-swa4aj","namespace":"kube-system","creationTimestamp":null},"data":{"auth-extra-groups":"c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=","expiration":"MjAxOS0xMS0yOVQxNjozMTozN1o=","token-id":"c3dhNGFq","token-secret":"amp6NzBkdjI5bGtmZzJnMg==","usage-bootstrap-authentication":"dHJ1ZQ==","usage-bootstrap-signing":"dHJ1ZQ=="},"type":"bootstrap.kubernetes.io/token"}
I1129 15:32:12.971549    8460 round_trippers.go:423] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets'
I1129 15:32:12.971990    8460 round_trippers.go:443] POST https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 15:32:12.972002    8460 round_trippers.go:449] Response Headers:
I1129 15:32:52.972597    8460 request.go:968] Request Body: {"kind":"Secret","apiVersion":"v1","metadata":{"name":"bootstrap-token-swa4aj","namespace":"kube-system","creationTimestamp":null},"data":{"auth-extra-groups":"c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=","expiration":"MjAxOS0xMS0yOVQxNjozMTozN1o=","token-id":"c3dhNGFq","token-secret":"amp6NzBkdjI5bGtmZzJnMg==","usage-bootstrap-authentication":"dHJ1ZQ==","usage-bootstrap-signing":"dHJ1ZQ=="},"type":"bootstrap.kubernetes.io/token"}
I1129 15:32:52.972678    8460 round_trippers.go:423] curl -k -v -XPOST  -H "Content-Type: application/json" -H "User-Agent: kubeadm/v1.16.2 (linux/amd64) kubernetes/c97fe50" -H "Accept: application/json, */*" 'https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets'
I1129 15:32:52.973374    8460 round_trippers.go:443] POST https://192.168.10.184:6443/api/v1/namespaces/kube-system/secrets  in 0 milliseconds
I1129 15:32:52.973402    8460 round_trippers.go:449] Response Headers:
timed out waiting for the condition
```

**Comment by mooperd** [comment]
I don't see anything binding to any port with `netstat -tulpn` on 192.168.10.184.

**Comment by kron4eg** [comment]
do you see containers are up (with `docker ps`)? kube-api, kube-scheduler and so on.

**Comment by mooperd** [comment]
There is nothing there

```
ubuntu@andrew-cp-1:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

The images have been pulled however.
```
ubuntu@andrew-cp-1:~$ sudo docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.16.2             8454cbe08dc9        6 weeks ago         86.1MB
k8s.gcr.io/kube-apiserver            v1.16.2             c2c9a0406787        6 weeks ago         217MB
k8s.gcr.io/kube-controller-manager   v1.16.2             6e4bffa46d70        6 weeks ago         163MB
k8s.gcr.io/kube-scheduler            v1.16.2             ebac1ae204a2        6 weeks ago         87.3MB
k8s.gcr.io/etcd                      3.3.15-0            b2756210eeab        2 months ago        247MB
k8s.gcr.io/coredns                   1.6.2               bf261d157914        3 months ago        44.1MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        23 months ago       742kB
```

I couldn't find anything interesting in the docker logs:

```
$ journalctl -u docker.service
-- Logs begin at Fri 2019-11-29 15:18:00 UTC, end at Fri 2019-11-29 17:20:36 UTC. --
Nov 29 15:19:07 andrew-cp-1 systemd[1]: Starting Docker Application Container Engine...
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.115936420Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/res
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.145721691Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.145772101Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.145844183Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.145849959Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.146109188Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/c
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.146257266Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.146440873Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420601440, CONNECTING" mod
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.146734548Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420601440, READY" module=g
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.147072860Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/c
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.147228047Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.147365098Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42074ad90, CONNECTING" mod
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.148146512Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc42074ad90, READY" module=g
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.244120164Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.244371191Z" level=warning msg="Your kernel does not support swap memory limit"
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.244421047Z" level=warning msg="Your kernel does not support cgroup rt period"
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.244428688Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.244892705Z" level=info msg="Loading containers: start."
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.669870154Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Dae
Nov 29 15:19:07 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:07.911166860Z" level=info msg="Loading containers: done."
Nov 29 15:19:08 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:08.060597166Z" level=info msg="Docker daemon" commit=2d0083d graphdriver(s)=overlay2 version=18.09.7
Nov 29 15:19:08 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:08.061006703Z" level=info msg="Daemon has completed initialization"
Nov 29 15:19:08 andrew-cp-1 dockerd[3365]: time="2019-11-29T15:19:08.144121503Z" level=info msg="API listen on /var/run/docker.sock"
Nov 29 15:19:08 andrew-cp-1 systemd[1]: Started Docker Application Container Engine.
```

**Comment by xmudrii** [comment]
@mooperd Do you have any components preinstalled in your image? From [the output you posted above](https://github.com/kubermatic/kubeone/issues/740#issuecomment-559808275), I don't see any output from `apt-get`, which makes me think that components (Docker, kubelet, and kubeadm) are preinstalled.

Usually, that is okay too, but it is up to you to ensure that all components are configured correctly.

Since this is the case, can you please run `ls -l /etc/kubernetes/`? I'm wondering does the directory already exists and if it does, what's already inside. I'd recommend doing that before running `kubeone install`, so either recreate the infra or run `kubeone reset`.

**Comment by mooperd** [comment]
It seems that a `folder` field was missing in the config.yaml described in the documentation. I found an error `All fields in workspace are mandatory` in the Kubelet logs(`journalctl -xeu kubelet`). This pointed me towards this line:

https://github.com/kubernetes/kubernetes/blob/85f8005cf0966008473c81b462aa37d2bba828b7/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L393

In the docs you have this:
```
    [Workspace]
    server = "1.1.1.1"
    datacenter = "dc-1"
    default-datastore="exsi-nas"
    resourcepool-path="kubeone"
```

But it seems you need this:
```
    [Workspace]
    server = "1.1.1.1"
    datacenter = "dc-1"
    default-datastore="exsi-nas"
    resourcepool-path="kubeone"
    folder = "kubernetes"
```

I have a new error now:

```
WARN[19:16:43 UTC] error was: failed to deploy machine-controller: failed to ensure machine-controller *v1.Deployment: failed to create *v1.Deployment: Deployment.apps "machine-controller" is invalid: [spec.template.spec.containers[0].env[3].name: Invalid value: "192.168.10.10.username": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.template.spec.containers[0].env[4].name: Invalid value: "192.168.10.10.password": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')] 
```


journalctl -xeu kubelet
```
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is RESULT.
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/d
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/do
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/d
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/d
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/do
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/d
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: I1129 19:03:54.280338    5897 server.go:410] Version: v1.16.2
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: W1129 19:03:54.281599    5897 plugins.go:115] WARNING: vsphere built-in cloud provider is now deprecated. The vSphere provider is deprecated and will be removed 
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: E1129 19:03:54.281954    5897 vsphere.go:395] All fields in workspace are mandatory. vsphere.conf does not have the workspace specified correctly. cfg.Workspace:
Nov 29 19:03:54 andrew-cp-1 kubelet[5897]: F1129 19:03:54.282090    5897 server.go:271] failed to run Kubelet: could not init cloud provider "vsphere": All fields in workspace are mandatory. vsphere.conf 
Nov 29 19:03:54 andrew-cp-1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Nov 29 19:03:54 andrew-cp-1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**Comment by mooperd** [comment]
I think making "Folders" mandatory is a bug but it seems it's required by the vsphere provider.

**Comment by kron4eg** [comment]
```
WARN[19:16:43 UTC] error was: failed to deploy machine-controller: failed to ensure machine-controller *v1.Deployment: failed to create *v1.Deployment: Deployment.apps "machine-controller" is invalid: [spec.template.spec.containers[0].env[3].name: Invalid value: "192.168.10.10.username": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*'), spec.template.spec.containers[0].env[4].name: Invalid value: "192.168.10.10.password": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')]
````

Yeah, the name of the var is started from a digit. Is it possible that you replace 192.168.10.10 with domain name for your vSphere endpoint? That'd fix the issue.

**Comment by mooperd** [comment]
Actually - this issue weirdly evolved. I found the "started with digit" problem some time ago but then other problems came up.

Right now I am really stuck between Folders and Namespaces - I will create a new ticket once I am able to explain the problem clearly.
